name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
  NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: echo "NOTION_API_KEY=$NOTION_API_KEY" >> .env
      - run: echo "NOTION_DATABASE_ID=$NOTION_DATABASE_ID" >> .env
      - run: echo "NOTION_PAGE_ID=$NOTION_PAGE_ID" >> .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test