name: Continuous Integration
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test